momentohq/client-sdk-python

CONTRIBUTING.md
README.md

README.md - https://github.com/momentohq/client-sdk-python/blob/chore/updateReadme/README.md
CONTRIBUTING.md - https://github.com/momentohq/client-sdk-python/blob/chore/updateReadme/CONTRIBUTING.md

chore: Add `CONTRIBUTING.md` and update `README.md`

---

.github/workflows/manual_release.yml
.github/workflows/pull_request_and_push.yml
setup.cfg
src/momento/aio/_add_header_client_interceptor.py
src/momento/aio/_scs_grpc_manager.py
tox.ini

chore: Add `agent` metadata

---

setup.cfg
src/momento/aio/_scs_data_client.py
src/momento/aio/simple_cache_client.py
src/momento/cache_operation_types.py
src/momento/simple_cache_client.py
tests/test_momento.py
tests/test_momento_async.py

Closes #84 
Expose delete method to the client. Update momento wire types, hook up gRPC to data client backend, and updates clients.

feat: Add delete functionality

---

poetry.lock

See the following links for more info:
https://github.com/momentohq/client-sdk-python/security/dependabot/5
https://www.openssl.org/news/secadv/20221101.txt

fix: update 'cryptography' pkg fix openssl vuln

---

examples/example_load_gen.py

feat: Modernize the Python load-gen example.

---

README.md

This is a temporary fix until I have time to migrate this to the badge system.

chore: Remove compatibility verbiage from README

---

Makefile
mypy.ini
poetry.lock
pyproject.toml
src/momento/internal/codegen.py
tests/momento/internal/test_codegen.py
tests/momento/simple_cache_client/shared_behaviors.py
tests/momento/simple_cache_client/shared_behaviors_async.py
tests/momento/simple_cache_client/test_scalar.py
tests/momento/simple_cache_client/test_scalar_async.py

* Establishes a pattern of shared tests for the coming collections expansion.
* Organizes the tests [pytest-describe](https://github.com/pytest-dev/pytest-describe) style by method.
This just moves tests around, no test was removed. It might be easier to review commit-by-commit with whitespace changes off.
Closes #189

test: Use shared tests for the scalar tests. Switch to pytest-describe style.

---

src/momento/internal/aio/_scs_control_client.py
src/momento/internal/synchronous/_scs_control_client.py
src/momento/responses/__init__.py
src/momento/responses/control/__init__.py
src/momento/responses/control/signing_keys.py
src/momento/simple_cache_client.py
src/momento/simple_cache_client_async.py
tests/momento/simple_cache_client/test_control.py
tests/momento/simple_cache_client/test_control_async.py

We partially revert 60df3d to add the signing key control operations
back. The `MomentoSigner` class remains in the other repository.

feat: add signing key control operations back in

---

src/momento/internal/codegen.py
tests/momento/internal/test_codegen.py

Add more regex replacements. Refactor `SimpleString` replacements into
separate data driven class.

chore: update codegen to handle examples in docstrings

---

src/momento/internal/_utilities/__init__.py
src/momento/internal/_utilities/_data_validation.py
src/momento/requests/collection_ttl.py
tests/momento/requests/test_collection_ttl.py
tests/momento/simple_cache_client/shared_behaviors.py
tests/momento/simple_cache_client/shared_behaviors_async.py
tests/momento/simple_cache_client/test_control.py
tests/momento/simple_cache_client/test_control_async.py
tests/momento/simple_cache_client/test_init.py
tests/momento/simple_cache_client/test_init_async.py
tests/momento/simple_cache_client/test_list.py
tests/momento/simple_cache_client/test_list_async.py
tests/momento/simple_cache_client/test_scalar.py
tests/momento/simple_cache_client/test_scalar_async.py

* Different error for wrong type vs wrong value.
* Consistently validate TTLs.

feat: Improve validation errors.

---

src/momento/internal/aio/_scs_data_client.py
src/momento/internal/synchronous/_scs_data_client.py
src/momento/responses/__init__.py
src/momento/responses/scalar_data/__init__.py
src/momento/responses/scalar_data/set_if_not_exists.py
src/momento/simple_cache_client.py
src/momento/simple_cache_client_async.py
tests/momento/simple_cache_client/test_scalar.py
tests/momento/simple_cache_client/test_scalar_async.py

feat: set_if_not_exists()

---

src/momento/internal/aio/_scs_data_client.py
src/momento/internal/synchronous/_scs_data_client.py

Also mark the methods as private.
Close #241

refactor: Make sure everything is using _collection_ttl_or_default_milliseconds

---

src/momento/config/configurations.py

Add v1 configurations and change latest to refer to v1.

chore: add v1 configurations

---

examples/Makefile
examples/poetry.lock
examples/prepy310/example.py
examples/prepy310/example_async.py
examples/py310/example.py
examples/py310/example_async.py
examples/py310/example_load_gen.py
examples/pyproject.toml
examples/requirements.txt

Updates examples to v0.24.0 and prefers v1 config.
Work towards https://github.com/momentohq/client-sdk-python/issues/294

chore: update examples

---

src/momento/__init__.py
src/momento/config/__init__.py
src/momento/errors/__init__.py
src/momento/requests/__init__.py
src/momento/responses/__init__.py

Documents the top level packages for better help in the IDE and REPL.
Closes #308

docs: document top level packages

---

src/momento/auth/credential_provider.py
src/momento/auth/momento_endpoint_resolver.py
tests/momento/auth/test_credential_provider.py

This commit adds support for v1 auth tokens, similar to https://github.com/momentohq/client-sdk-nodejs/pull/336.

feat: add support for v1 auth tokens

---

src/momento/cache_client.py
src/momento/cache_client_async.py
src/momento/internal/_utilities/_data_validation.py
src/momento/internal/aio/_scs_data_client.py
src/momento/internal/synchronous/_scs_data_client.py
src/momento/responses/__init__.py
src/momento/responses/data/sorted_set/get_rank.py
src/momento/responses/data/sorted_set/get_score.py
src/momento/responses/data/sorted_set/get_scores.py
tests/conftest.py
tests/momento/simple_cache_client/test_sorted_set.py
tests/momento/simple_cache_client/test_sorted_set_async.py

Add methods for getting the score of a sorted set value/values.
Add a method for getting the rank of a sorted set value.

feat: Add sorted set get score and rank

---

src/momento/cache_client.py
src/momento/cache_client_async.py
src/momento/internal/aio/_scs_data_client.py
src/momento/internal/synchronous/_scs_data_client.py
src/momento/responses/data/sorted_set/increment.py
src/momento/responses/data/sorted_set/remove_element.py
src/momento/responses/data/sorted_set/remove_elements.py
tests/momento/simple_cache_client/test_sorted_set.py
tests/momento/simple_cache_client/test_sorted_set_async.py

Add methods for removing elements from a sorted set.
Add a method incrementing a sorted set score.

feat: Add sorted set remove and increment

---

examples/vector-index/README.md
examples/vector-index/example.py

Added basic example for MVI to create index, list them, add items, search for them, and finally delete the index.

feat: add vanilla example for mvi

---

README.md

README is not templated for Python like other SDKs so missed this one.

chore: updating README to use factory method

---

examples/prepy310/topic_subscribe.py
examples/prepy310/topic_subscribe_async.py
examples/py310/topic_subscribe.py
examples/py310/topic_subscribe_async.py
src/momento/responses/pubsub/subscribe.py
src/momento/responses/pubsub/subscription_item.py
tests/momento/topic_client/test_topics.py
tests/momento/topic_client/test_topics_async.py

Addresses the python task in [#452](https://github.com/momentohq/dev-eco-issue-tracker/issues/452)

chore: update topic subscription response

---

README.template.md

Add backticks to API key mention.

docs: add markdown formatting to API key mention

---

examples/py310/example_load_gen.py

For https://github.com/momentohq/dev-eco-issue-tracker/issues/431

chore: update loadgen to be more specific for numberOfConcurrentRequests caveat

---

tests/conftest.py
tests/momento/vector_index_client/test_data.py
tests/momento/vector_index_client/test_data_async.py

Because the query vector was repeated, we factor that out to a
variable.

test: refactor search threshold test

---

examples/poetry.lock
examples/prepy310/vector_index.py
examples/prepy310/vector_index_async.py
examples/py310/doc-examples-python-apis.py
examples/py310/vector_index.py
examples/py310/vector_index_async.py
examples/pyproject.toml

Update examples for latest MVI updates:
- update core mvi example files
- update doc example snippets for list indexes update

chore: update examples for mvi updates

---

examples/poetry.lock
examples/py310/doc-examples-python-apis.py
examples/pyproject.toml

Adds an MVI API snippet for `search_and_fetch_vectors`.

chore: include search_and_fetch_vectors in mvi api snippets

---

pyproject.toml
src/momento/internal/aio/_vector_index_data_client.py
src/momento/internal/synchronous/_vector_index_data_client.py
src/momento/responses/vector_index/__init__.py
src/momento/responses/vector_index/data/get_item_and_fetch_vectors_batch.py
src/momento/responses/vector_index/data/get_item_batch.py
src/momento/responses/vector_index/data/item.py
src/momento/vector_index_client.py
src/momento/vector_index_client_async.py
tests/momento/vector_index_client/test_data.py
tests/momento/vector_index_client/test_data_async.py

Adds MVI methods for get item batch and get item and fetch vectors
batch and integration tests.

feat: implement get item batch and variant

---

poetry.lock
pyproject.toml
src/momento/internal/aio/_vector_index_data_client.py
src/momento/internal/synchronous/_vector_index_data_client.py
src/momento/responses/vector_index/__init__.py
src/momento/responses/vector_index/data/count_items.py
src/momento/vector_index_client.py
src/momento/vector_index_client_async.py
tests/momento/vector_index_client/test_data.py
tests/momento/vector_index_client/test_data_async.py

Adds MVI data operation to count items in an index, including top
level methods, response types, and integration tests.

feat: mvi count items

---

poetry.lock
pyproject.toml
src/momento/requests/vector_index/filters.py
tests/momento/vector_index_client/test_data.py
tests/momento/vector_index_client/test_data_async.py

Bumps the python proto dependency and implements the MVI filter expression `IdInSet`. This filter expression is satisfied when an item has an id that is in the set provided by the user. We also add integration tests for this filter.

feat: mvi id in set filter expression

---

examples/py310/doc-examples-python-apis.py

We add example API snippets for MVI filter expressions. This example
follows the existing JS snippets.

chore: add mvi filter expression example snippets

---

src/momento/responses/__init__.py

https://github.com/momentohq/client-sdk-python/pull/468 was an incomplete fix

fix: make sure to import GenerateDisposableToken response class before exporting it in init file

---

examples/poetry.lock
examples/py310/doc-examples-python-apis.py
examples/pyproject.toml

Also updates the import line for the GenerateDisposableToken response class to match the others

chore: update momento version in examples
