momentohq/client-sdk-python

src/momento/_async_utils.py, src/momento/aio/simple_cache_client.py, src/momento/simple_cache_client.py, tests/test_momento.py, tests/test_momento_async.py
There is a bug in grpc's packaging of native artifacts that relates
to certain versions of python 3 and the default wheel tags.
Investigation is ongoing, but in the meantime there is a simple
mitigation that users can try to get around the issue for local
development workflows.
Relates to: https://github.com/grpc/grpc/issues/28387
Example error with this change:
```
➜  python-demo venv/bin/python3 ./some_project/main.py 
There is an issue on M1 macs between GRPC native packaging and Python wheel tags. See https://github.com/grpc/grpc/issues/28387
TO WORK AROUND, please install Rosetta 2 and re-run with:
arch -x86_64 /Users/kenny/python-demo/venv/bin/python3 ./some_project/main.py
Traceback (most recent call last):
File "/Users/kenny/python-demo/./some_project/main.py", line 5, in <module> …
```
=> fix: mitigate m1 incompatibility

.github/workflows/manual_release.yml
With @eaddingtonwhite help, moved the PyPI auth token to the org level secret.
Since secret names need to be unique at the org level, this repo's secret name got updated to `PYTHON_CUSTOMER_SDK_PYPI_TOKEN`.
=> chore: Update secret variable name for PyPI auth token

CONTRIBUTING.md
The previous PR #95 updated the tox envlist to be in the standard format. This PR updates the documentation to be consistent with that.
=> chore: Update CONTRIBUTING documentation to reflect latest tox envlist.

src/momento/aio/simple_cache_client.py, src/momento/cache_operation_types.py, src/momento/incubating/__init__.py, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/aio/utils.py, src/momento/incubating/cache_operation_types.py, src/momento/incubating/simple_cache_client.py, src/momento/simple_cache_client.py, tests/incubating/test_momento.py, tests/incubating/test_momento_async.py, tests/test_momento.py, tests/test_momento_async.py
Closes #85 
Adds a dictionary data type API with a non-production client side implementation. The methods added to the client are:
1. `dictionary_get`: retrieve a value from a dictionary in the cache
2. `dictionary_get_all`: retrieve the whole dictionary from the cache
3.  `dictionary_set`: store key-value pairs in a dictionary (upsert)
=> feat(#85): MVP dictionary API

src/momento/_momento_logger.py
quit stripping `*args` from the logging functions.
Relates to https://github.com/momentohq/client-sdk-python/issues/101
=> fix: momento logger function definitions

src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/aio/utils.py, src/momento/incubating/cache_operation_types.py, tests/incubating/test_momento.py, tests/incubating/test_momento_async.py
Changes `value` method of `CacheDictionaryGetAllResponse` to support unmarshalling keys to strings or bytes. Intended usage is as follows:
```
client.dictionary_set("my-cache", "my-dictionary", {"key1": "value1", "key2": "value2"})
get_all_response = client.dictionary_get_all("my-cache", "my-dictionary")
stored_dictionary = get_all_response.value()
value = stored_dictionary["key1"].value()) # value = "value1"
```
As well as:
```
client.dictionary_set("my-cache", "my-dictionary", {b"key1": b"key2", b"key3": b"key4"})
get_all_response = client.dictionary_get_all("my-cache", "my-dictionary")
stored_dictionary = get_all_response.value(keys_as_bytes=True)
value = stored_dictionary[b"key1"].value_as_bytes() # value = b"value1"
```
Will refine convenience methods further pending customer …
=> fix: incubating dictionary convenience methods

src/momento/incubating/README.md, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/aio/utils.py, src/momento/incubating/cache_operation_types.py, tests/incubating/test_momento.py, tests/incubating/test_momento_async.py
Align CacheDictionaryGetAll with latest spec.
For the incubating dictionary type, we are limiting the convenience functions to returning either string->string or bytes->bytes. This simplifies the API to returned dictionaries for the most common use cases. See the latest incubating README for changes in user experience.
=> chore: Align dictionary interface with latest spec

src/momento/_utilities/_data_validation.py, src/momento/_utilities/_serialization.py, src/momento/incubating/README.md, src/momento/incubating/_utilities/_serialization.py, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/cache_operation_types.py, src/momento/incubating/simple_cache_client.py, tests/incubating/test_momento.py, tests/incubating/test_momento_async.py
Closes #109 
Adds to the dictionary incubating methods with:
- multi-get: `dictionary_multi_get("my-cache", "my-dictionary", "key1", "key2", "key3")`
- unary-set: `dictionary_set("my-cache", "my-dictionary", "key", "value", refresh_ttl=False)`, cf `dictionary_multi_set("my-cache", "my-dictionary", dictionary={"key1": "value1", "key2": "value2", "key3": "value3"}, refresh_ttl=False)`
- TTL: `dictionary_set("my-cache", "my-dictionary", "key", "value", ttl_seconds=60, refresh_ttl=False)` per discussions we have had.
See `src/momento/incubating/README.md` for a listing of the dictionary functionality. In particular see the response types:
```python
>>> get_response = client.dictionary_get("my-cache", "my-dictionary", "key1")
>>> get_response
CacheDictionaryGetUnaryResponse(value=b'value1', …
```
=> feat: dictionary multi-get, unary set, and TTL.

src/momento/_utilities/_data_validation.py, src/momento/aio/_add_header_client_interceptor.py, src/momento/aio/_scs_control_client.py, src/momento/aio/_scs_data_client.py, src/momento/aio/simple_cache_client.py, src/momento/cache_operation_types.py, src/momento/incubating/simple_cache_client.py, src/momento/momento_signer.py, src/momento/simple_cache_client.py, tests/test_momento.py, tests/test_momento_async.py, tests/test_momento_signer.py
Closes #111 
I refactored `multi_get` and `multi_set` to use method signatures and responses like those we approved for the dictionary type. In short:
```python
client.multi_set(cache_name="my-cache", items={"key1": "value1", "key2": "value2"}, ttl_seconds=60)
response = client.multi_get("my-cache", "key1", "key2", "key3")
response.status() # [<CacheGetStatus.HIT: 1>, <CacheGetStatus.HIT: 1>, <CacheGetStatus.MISS: 2>]
response.values() # ["value1", "value2", None]
response.to_list() # CacheMultiGetResponse(responses=[CacheGetResponse(value=b'value1', result=<CacheGetStatus.HIT: 1>), CacheGetResponse(value=b'value2', result=<CacheGetStatus.HIT: 1>), CacheGetResponse(value=None, result=<CacheGetStatus:MISS 2>)])
```
=> chore: Refactor multi-get and multi-set

src/momento/aio/_scs_control_client.py, src/momento/aio/_scs_data_client.py, src/momento/aio/_scs_grpc_manager.py, src/momento/cache_operation_types.py, src/momento/incubating/README.md, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/cache_operation_types.py, tests/test_momento.py
Closes #113 
Most of the response objects were lacking `__repr__` methods. Before users could expect output like this:
```python
>>> client.get("my-cache", "my-key")
<momento.cache_client_operations.CacheGetResponse at 0x7f8e6d292770>
```
which is not very helpful. Now we have output like this:
```python
>>> client.get("my-cache", "my-key")
CacheGetResponse(value=b'my-value, status=<CacheGetStatus.HIT: 1>)
>>> client.multi_get("my-cache", "key1", "key2")
CacheMultiGetResponse(responses=[CacheGetResponse(value=b'value1', status=<CacheGetStatus.HIT: 1>), CacheGetResponse(value=b'value2', status=<CacheGetStatus.HIT: 1>)])
```
which is much more informative and civilized.
=> chore: Add repr and str methods to response objects

src/momento/aio/_scs_data_client.py, src/momento/aio/simple_cache_client.py, src/momento/cache_operation_types.py, src/momento/incubating/README.md, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/simple_cache_client.py, src/momento/simple_cache_client.py, tests/incubating/test_dictionary.py, tests/incubating/test_dictionary_async.py, tests/test_momento.py, tests/test_momento_async.py
The previous naming convention preferred modifiers before commands, as
in `multi_get`, `dictionary_multi_get`. This ordering makes it
difficult to group commands under the IDE and in documentation. The
new ordering `get_multi`, `dictionary_get_multi` eases this.
With this way, now the following will be completions of
`dictionary_get`:
`dictionary_get`, `dictionary_get_multi`, `dictionary_get_all`
=> chore: rename "multi" methods and responses.

requirements-dev.txt, tests/incubating/test_dictionary.py, tests/incubating/test_dictionary_async.py, tests/incubating/test_exists.py, tests/incubating/test_exists_async.py, tests/test_momento.py, tests/test_momento_async.py, tests/test_momento_signer.py, tests/utils.py
Use random data in integration tests. The previous code used specific strings for keys and values. Because the integration tests run repeatedly on the same cache, this could cause undesirable behavior if the same tests are repeated in quick succession.
Work towards #117
=> chore: use guids in tests

src/momento/aio/simple_cache_client.py, src/momento/incubating/aio/simple_cache_client.py, src/momento/incubating/simple_cache_client.py, src/momento/simple_cache_client.py, tests/conftest.py, tests/incubating/test_dictionary.py, tests/incubating/test_dictionary_async.py, tests/incubating/test_exists.py, tests/incubating/test_exists_async.py, tests/test_momento.py, tests/test_momento_async.py
The `init` functions to build the cache clients are unnecessary. Because python allows keyword arguments, we can pass any and all configuration options in the constructor.
Work towards #117
=> refactor: remove init functions

.gitignore, poetry.lock, pyproject.toml
Fixes to address vulns found by dependabot in gRPC. Will need to make another follow-up pr into `examples` folder after to get this fix as well.  Also went ahead and pinned all run time dependencies for our project in `pyproject.toml` like we have been doing with our other SDK's.
=> fix: bump and pin libs to resolve grpc vuln

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-release-branch.yml
Pins the ubuntu version to 20.04. Previously we used `ubuntu-latest`; GitHub started pointing this from 20.04 to 22.04 in October and the integration tests started failing. We have timeboxed an investigation into why 22.04 fails, but remains inconclusive. Hence in the meantime we revert to 20.04. We also pin the poetry dependency as a matter of good practice.
=> fix: pin ubuntu and poetry ci dependencies

examples/example_load_gen.py
The load-gen script passes through a lot of individual variables which makes it unwieldy to change its options. Instead, make them available as BasicPythonLoadGen attributes.
* Group config variables in BasicPythonLoadGenOptions.
* Make it an BasicPythonLoadGen attribute.
* Make BasicPythonLoadGenContext a BasicPythonLoadGen attribute.
=> refactor: Reduce pass-through args in BasicPythonLoadGen.

mypy.ini, src/momento/aio/_retry_interceptor.py, src/momento/internal/synchronous/_retry_interceptor.py, src/momento/internal/synchronous/_scs_grpc_manager.py
In an earlier commit we made some changes to the implementation
of the synchronous client to use the grpc synchronous API directly,
rather than wrapping the asyncio API, which was causing problems
in environments that used other asyncio libraries.
During the rollout of that change we mistakenly lost the retry
capabilities that we have in the asyncio client.  This commit
adds the retry suppport back in for the sync client.
This implementation is not DRY and we need to clean it up as we
are doing the work to introduce Configuration, but this will
at least unblock users for now.
=> fix: re-introduce retry interceptor for synchronous client

src/momento/_utilities/_data_validation.py, src/momento/aio/_scs_control_client.py, src/momento/aio/_scs_data_client.py, src/momento/aio/_scs_grpc_manager.py, src/momento/aio/simple_cache_client.py, src/momento/auth/credential_provider.py, src/momento/auth/momento_endpoint_resolver.py, src/momento/config/configuration.py, src/momento/config/configurations.py, src/momento/config/transport/grpc_configuration.py, src/momento/config/transport/transport_strategy.py, src/momento/internal/common/_data_client_ops.py, src/momento/internal/synchronous/_scs_control_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/simple_cache_client.py, tests/conftest.py, tests/test_momento.py, tests/test_momento_async.py
This commit updates the Python SDK to use the [standard configuration classes](https://github.com/momentohq/standards-and-practices/blob/main/docs/client-specifications/configuration.md) and the credential provider interface. It also updates ttl and client deadline values so they are expressed as `timedelta` objects instead of integers. Finally, unit tests that made assertions about exception messages have also been updated, as they were silently ignoring the message text.
=> feat: add configuration classes

src/momento/requests/__init__.py, src/momento/requests/collection_ttl.py, tests/momento/requests/test_collection_ttl.py
This ports the `CollectionTtl` class from the .NET SDK. This class is
used as an argument to all the mutative collections APIs.
Closes #187
=> chore: add collection ttl data class

mypy.ini, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/common/_data_client_ops.py, src/momento/internal/common/_data_client_scalar_ops.py, src/momento/internal/synchronous/_scs_data_client.py
This will avoid a monolithic file and conflicts as we add collections. Each collection has its own file.
Closes #198
=> refactor: Extract internal scalar op support functions.

src/momento/responses/__init__.py, src/momento/responses/response.py, src/momento/responses/scalar_data/delete.py, src/momento/responses/scalar_data/get.py, src/momento/responses/scalar_data/set.py
This lets us get the type checks right for shared behaviors of all methods.
=> refactor: Add a CacheResponse abstract superclass for all responses.

src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py
Since we will be working concurrently on data structure methods, we
should reduce the likelihood of merge conflicts. By grouping the
methods under these comments we will make that less likely.
=> chore: add comments as fenceposts to reduce merge conflicts

Makefile
The echo in this target was a placeholder and produces an error. We
remove it.
=> fix: remove extraneous echo from make target

src/momento/responses/scalar_data/delete.py, src/momento/responses/scalar_data/get.py, src/momento/responses/scalar_data/set.py
A few typos in the scalar response docs.
* "create X request" -> "cache X request"
* CacheDeleteResponse was talking about a set request.
=> fix: Scalar cache response description of the request.

.github/workflows/on-push-to-release-branch.yml
The CI caches clobber each other on release because all python
versions share the same cache name. We create a unique cache name
derived from the python version and commit hash as in the
`on-pull-request` workflow.
=> fix: isolate test cache names on push to release

.github/workflows/on-push-to-main-branch.yml
We have updated the examples and forked based on python version. In
the previous example update we referenced the py310 synchronous
example as the canonical one. We update that here as well.
=> fix: update example location

src/momento/simple_cache_client_async.py
Prefer pythonic property for data client accessor in the async
client. This will also make converting the async to sync clients
easier.
=> chore: use property for next data client

pyproject.toml
Pinned dependencies invite conflicts with other libraries with the same dependencies.
Keep the minimum version, but relax the max. Stay within the major version.
=> fix: Unpin dependencies to avoid library conflicts.

Makefile, poetry.lock, src/momento/internal/codegen.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/momento/internal/test_codegen.py
We update the async client and codegen module to generate the
synchronous client from the async one.
Updates the Makefile target to always generate the synchronous client from the asynchronous one.
Also refactors the `gen-sync` Makefile target to run format.
Closes #204
=> chore: align clients

src/momento/responses/scalar_data/delete.py, src/momento/responses/scalar_data/get.py, src/momento/responses/scalar_data/set.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py
Cutting and pasting these docs will become untenable as the interface expands. Document the pattern in SimpleCacheClient and refer back to it.
=> docs: Move explaining how to use responses into SimpleCacheClient.

src/momento/requests/collection_ttl.py, tests/momento/requests/test_collection_ttl.py
We do this inside CollectionTtl so we don't have to check it in every collection method.
I excluded 0 because why would you want that? We can allow it later if someone really needs it.
Closes #222
=> feat: Validate the CollectionTtl.ttl is positive.

Makefile, poetry.lock, pyproject.toml, src/momento/internal/_utilities/__init__.py, src/momento/internal/_utilities/_data_validation.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/responses/__init__.py, src/momento/responses/list_data/__init__.py, src/momento/responses/list_data/list_concatenate_back.py, src/momento/responses/list_data/list_fetch.py, src/momento/responses/scalar_data/delete.py, src/momento/responses/scalar_data/get.py, src/momento/responses/scalar_data/set.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, src/momento/typing.py, tests/conftest.py, tests/momento/simple_cache_client/shared_behaviors.py, tests/momento/simple_cache_client/shared_behaviors_async.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py
This adds the minimum of collections to exercise how we add them going forward and avoid colliding when working in parallel. listFetch and listConcatenateBack.
**Note**: all the duplicated synchronous files can be ignored for review purpose, they're all generated from the async code.
* Upgrade wire types to one that supports collections and new scalar methods.
* Unpin the dependency to be a good citizen.
* Add list types
* Add some helpful collections fixtures
* Add cache name type (didn't use it everywhere)
* Add some helpful trace logging wrappers.
For #174 and #184
=> feat: First collections methods.

src/momento/internal/_utilities/_data_validation.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/responses/__init__.py, src/momento/responses/list_data/__init__.py, src/momento/responses/list_data/list_concatenate_front.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/conftest.py, tests/momento/simple_cache_client/shared_behaviors.py, tests/momento/simple_cache_client/shared_behaviors_async.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py
This PR is to establish an agreed upon doc style for the collection methods.
* Document all the list methods.
* Test list name validation (the tests were there but not used)
* Validate that names are not empty strings
* Something was doing it at a lower level for cache names, but we don't have that for collection names.
For #174
=> feat: list_concatenate_front()

src/momento/responses/__init__.py, src/momento/responses/dictionary_data/__init__.py, src/momento/responses/dictionary_data/dictionary_fetch.py, src/momento/responses/dictionary_data/dictionary_get_field.py, src/momento/responses/dictionary_data/dictionary_get_fields.py, src/momento/responses/dictionary_data/dictionary_increment.py, src/momento/responses/dictionary_data/dictionary_remove_field.py, src/momento/responses/dictionary_data/dictionary_remove_fields.py, src/momento/responses/dictionary_data/dictionary_set_field.py, src/momento/responses/dictionary_data/dictionary_set_fields.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, src/momento/typing.py
Stub out the dictionary API and document it; also implement port of response types. This covers:
- `dictionary_fetch`
- `dictionary_get_field`
- `dictionary_get_fields`
- `dictionary_increment`
- `dictionary_set_field`
- `dictionary_set_fields`
- `dictionary_remove_field`
- `dictionary_remove_fields`
API, documentation, and response types will be subject to change on implementation.
=> feat: dictionary stub implementation

src/momento/auth/__init__.py, src/momento/auth/credential_provider.py, src/momento/internal/aio/_scs_control_client.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_control_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/conftest.py, tests/momento/auth/test_credential_provider.py, tests/momento/simple_cache_client/shared_behaviors.py, tests/momento/simple_cache_client/shared_behaviors_async.py, tests/momento/simple_cache_client/test_control.py, tests/momento/simple_cache_client/test_control_async.py, tests/momento/simple_cache_client/test_init.py, tests/momento/simple_cache_client/test_init_async.py
Make credential provider pythonic. Add the equivalent of StringMomentoAuthProvider as a static constructor.
Closes #223
=> chore: refactor credential provider, add string provider

tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py
The credential provider refactor did not touch the list tests. We
update those.
=> fix: fix tests to use latest credential provider

src/momento/errors/error_converter.py, src/momento/internal/_utilities/_data_validation.py, src/momento/internal/aio/_add_header_client_interceptor.py, src/momento/internal/aio/_retry_interceptor.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/codegen.py, src/momento/internal/synchronous/_add_header_client_interceptor.py, src/momento/internal/synchronous/_retry_interceptor.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/internal/synchronous/_utilities.py, src/momento/requests/collection_ttl.py, src/momento/responses/control/list_caches.py, src/momento/responses/control/signing_keys.py, src/momento/typing.py
Use `__future__.annotations` to use type hint syntax from 3.8+.
Closes #248
=> feat: use modern python type hint syntax

.github/workflows/on-push-to-main-branch.yml, README.template.md
Eventually we need to have multiple examples in the README:
- Python 3.10+ with pattern matching
- Python < 3.10 without pattern matching
- async client
- sync client
Since we are only displaying one example right now, this PR adds the sync
example for Python < 3.10. That way we have at least one example
compatible across all Python versions and one example with the pattern
matching.
=> chore: add a hardcoded example for prepy310 to the README template

src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/momento/simple_cache_client/test_dictionary.py, tests/momento/simple_cache_client/test_dictionary_async.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py, tests/momento/simple_cache_client/test_scalar.py, tests/momento/simple_cache_client/test_scalar_async.py, tests/momento/simple_cache_client/test_set.py, tests/momento/simple_cache_client/test_set_async.py
This avoids having to worry about argument order.
I left set and set_if_not_exists alone becausae it would be a backwards incompat change.
Also
* set_add_elements() and set_remove_elements() was being passed a list, not a set.
Closes #255
=> feat: Enforce keyword args for optional arguments.

src/momento/internal/codegen.py, tests/momento/internal/test_codegen.py
We update codegen to handle lines with:
`from typing import Awaitable`
by removing the statement entirely.
=> fix: codegen import with one import from that is async

pyproject.toml, tests/asserts.py, tests/conftest.py, tests/momento/simple_cache_client/shared_behaviors.py, tests/momento/simple_cache_client/shared_behaviors_async.py, tests/momento/simple_cache_client/test_dictionary.py, tests/momento/simple_cache_client/test_dictionary_async.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py, tests/momento/simple_cache_client/test_scalar.py, tests/momento/simple_cache_client/test_scalar_async.py, tests/momento/simple_cache_client/test_set.py, tests/momento/simple_cache_client/test_set_async.py
* Switch to a style that supports named arguments and is easier to understand.
* Only pass the necessary arguments to fixtures.
* For any test which needs to use the same cache, the fixture gets the cache name.
Also: other misc type issues in the tests.
Closes #254
=> refactor: Clean up the signatures of shared behaviors.

src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/responses/control/list_caches.py, src/momento/responses/control/signing_keys.py, src/momento/responses/dictionary_data/dictionary_fetch.py, src/momento/responses/dictionary_data/dictionary_get_field.py, src/momento/responses/dictionary_data/dictionary_get_fields.py, src/momento/responses/dictionary_data/dictionary_increment.py, src/momento/responses/list_data/list_concatenate_back.py, src/momento/responses/list_data/list_concatenate_front.py, src/momento/responses/list_data/list_fetch.py, src/momento/responses/list_data/list_length.py, src/momento/responses/list_data/list_pop_back.py, src/momento/responses/list_data/list_pop_front.py, src/momento/responses/list_data/list_push_back.py, src/momento/responses/list_data/list_push_front.py, src/momento/responses/response.py, src/momento/responses/scalar_data/get.py, tests/momento/responses/test_cache_dictionary_fetch_response.py, tests/momento/responses/test_cache_get_response.py, tests/momento/responses/test_cache_list_fetch_response.py, tests/momento/responses/test_cache_set_fetch_response.py
Updates `__repr__` to be an evaluable string representation of the object, as per the Python spec. `__str__` still truncates, and now also truncates collections both in their elements and number of elements.
Closes #194
=> chore: refine str and repr for collections

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-release-branch.yml, Makefile, src/momento/internal/codegen.py, tests/conftest.py, tests/momento/aio/client_interceptor_test.py, tests/momento/auth/test_credential_provider.py, tests/momento/config/test_config.py, tests/momento/requests/test_collection_ttl.py, tests/momento/simple_cache_client/test_control.py, tests/momento/simple_cache_client/test_control_async.py, tests/momento/simple_cache_client/test_dictionary.py, tests/momento/simple_cache_client/test_dictionary_async.py, tests/momento/simple_cache_client/test_init.py, tests/momento/simple_cache_client/test_init_async.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py, tests/momento/simple_cache_client/test_set.py, tests/momento/simple_cache_client/test_set_async.py
This PR fixes the type hint errors throughout the tests and enables `mypy` and `flake8` on the tests in the Makefile and CI.
- chore: fix mypy errors on tests
- chore: enable mypy and flake8 on tests in Makefile
- chore: run mypy and flake8 on tests in CI
Closes #236
=> chore: enable linting on tests

src/momento/internal/aio/_scs_control_client.py, src/momento/internal/synchronous/_scs_control_client.py, src/momento/responses/control/list_caches.py, src/momento/responses/control/signing_keys.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/momento/simple_cache_client/test_control.py, tests/momento/simple_cache_client/test_control_async.py
Remove the page token from the list caches and list signing keys methods. The paging functionality is currently unimplemented and the paging logic could potentially be hidden from the user after it is.
=> chore: remove pagination from list caches and list signing keys

src/momento/internal/codegen.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py
Add an example of how to instantiate a client to the simple cache client docs.
Add a new string replacement to the code generation to replace any instance of 'SimpleCacheClientAsync' with 'SimpleCacheClient' to let the example doc be translated correctly.
=> chore: add client instantiation example to docs

src/momento/internal/_utilities/_data_validation.py, tests/momento/simple_cache_client/test_dictionary.py, tests/momento/simple_cache_client/test_dictionary_async.py, tests/momento/simple_cache_client/test_set.py, tests/momento/simple_cache_client/test_set_async.py
Align the default error messages in _data_validation.py with what the errors represent.
=> chore: fix as-bytes error messages

src/momento/__init__.py, src/momento/config/__init__.py, src/momento/config/configurations.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py, tests/conftest.py
Rolls up configurations and CredentialProvider to top level `momento`
package. Updates documentation of inline examples.
Closes #284
=> chore: improve imports for configurations and CredentialProvider

src/momento/responses/data/dictionary/get_fields.py, src/momento/responses/data/list/fetch.py, tests/momento/responses/test_cache_list_fetch_response.py, tests/momento/simple_cache_client/test_list.py, tests/momento/simple_cache_client/test_list_async.py
Audit the response hierarchy checking for incorrect parent classes and
checking the class fields for consistency.
Closes #286
=> fix: audit response hierarchy

pyproject.toml, src/momento/config/configuration.py, src/momento/config/configurations.py, src/momento/internal/aio/_retry_interceptor.py, src/momento/internal/aio/_scs_control_client.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_retry_interceptor.py, src/momento/internal/synchronous/_scs_control_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/retry/__init__.py, src/momento/retry/default_eligibility_strategy.py, src/momento/retry/eligibility_strategy.py, src/momento/retry/fixed_count_retry_strategy.py, src/momento/retry/retry_strategy.py, src/momento/retry/retryable_props.py, src/momento/simple_cache_client.py, src/momento/simple_cache_client_async.py
Add abstract EligibilityStrategy class that determines whether a grpc call can be retried based on the type of call and the error encountered.
Add abstract RetryStrategy class that uses an EligibilityStrategy to determine if a call can be retried and outputs a time to wait before retrying.
Add default implementations of the retry and eligibility strategies that have no wait time.
Update the configurations to take a retry strategy and set the number of retries to 3 by default. That is, 1 initial call and up to 3 retries on top of that.
=> feat: make the retry logic configurable

README.template.md, src/momento/__init__.py, src/momento/logs.py
Do nothing instead of raising an error if a log method is already defined in the add_logging_level method.
Call initialize_momento_logging in __init__.py to add trace logging.
Add a section to the readme that explains the trace logging and has an example of how to enable it.
=> chore: add trace level logging

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-main-branch.yml
With the 1.0 SDK release, the project is now `stable`.
=> chore: upgrade project stability to stable

src/momento/internal/aio/_retry_interceptor.py, src/momento/internal/synchronous/_retry_interceptor.py
This commit changes the retry interceptors so that they don't call
into the retry strategy if the status code is OK.  The main motivation
is that prior to this change we were emitting a debug log message
on every request, even if they were successful.  But generally
speaking there is also no reason to incur any cost overhead for
the retry computations if the request already succeeded.
=> fix: don't call retry logic on OK status codes

poetry.lock, pyproject.toml, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py
Update the Momento wire types dependency to allow the creation of sorted set methods.
Fix the increment request syntax that has changed with the new wire types version.
Avoid updating any other dependency because one of them causes a regression that prevents most of the tests from running.
=> chore: Update the Momento wire types dependency

.github/workflows/on-push-to-release-branch.yml
The `on-push-to-release-branch` workflow should not be able to be run manually. It should only be run when a commit gets pushed to release
=> fix: remove manual release footgun

poetry.lock, pyproject.toml
This allows installation on systems using `grpcio` versions as low as
1.46.0. Integration tests run locally with this version passed.
[Previously](https://github.com/momentohq/client-sdk-python/pull/140)
we had bumped the `gprcio` dependency after a security vulnerability
was reported for `protobuf-python`. Because that is a transitive
dependency of `momento-wire-types` and not `grpcio`, we did not need
to bump the `grpcio` dependency at that time.
=> feat: relax grpcio dependency lower bound

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-release-branch.yml, Makefile, poetry.lock, pyproject.toml, src/momento/internal/aio/_scs_control_client.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_control_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/responses/control/cache/list.py
The latest `momento-wire-types` can support both `protobuf<3.20` and
later versions. This PR bumps to that version and updates the import
statements as appropriate.
=> feat: support protobuf<3.20

poetry.lock, pyproject.toml, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py
Per the
[docs](https://docs.python.org/3.12/library/importlib.metadata.html):
> importlib.metadata is a library that provides access to the metadata
> of an installed Distribution Package, such as its entry points or its
> top-level names (Import Packages, modules, if any). Built in part on
> Python’s import system, this library intends to replace similar
> functionality in the entry point API and metadata API of
> pkg_resources. Along with importlib.resources, this package can
> eliminate the need to use the older and less efficient pkg_resources
> package.
> 
> importlib.metadata operates on third-party distribution packages
> installed into Python’s site-packages directory via tools such as
> pip. Specifically, it works with distributions with discoverable
> dist-info or egg-info …
=> fix: prefer `importlib_metadata` to deprecated pkg_resources

poetry.lock, pyproject.toml, src/momento/internal/_utilities/__init__.py, src/momento/internal/_utilities/_momento_version.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py, tests/momento/internal/_utilities/test_momento_version.py
Python 3.8 introduced a standard library `importlib.metadata` to
introspect package versions at runtime. Because of this, we only need
`importlib_metadata`, the backported library for python versions
<3.8. We modify the project requirements to only install this on those
versions, and to use the standard library when available.
=> chore: restrict importlib_metadata package to python < 3.8

examples/config/prometheus.yml, examples/docker-compose.yaml, examples/grafana/dashboards/scalar.json, examples/grafana/provisioning/dashboards/dashboards.yml, examples/grafana/provisioning/datasources/datasource.yml, examples/observability.py, examples/utils/instrumentation.py
- Add traces with open telemetry
1. Run  `docker-compose up -d` to start the zipkin server
2. Run `MOMENTO_AUTH_TOKEN=<token> python3 observability.py` using the cli  
3. Verify zipkins running at `http://localhost:9411`.
=> feat: add traces with open telemetry

CONTRIBUTING.md, src/momento/cache_client.py, src/momento/cache_client_async.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/responses/data/sorted_set/increment.py, src/momento/responses/data/sorted_set/increment_score.py, tests/momento/cache_client/test_sorted_set.py, tests/momento/cache_client/test_sorted_set_async.py
The Python SDK had implemented increment support for sorted sets
using the name `sorted_set_increment`, when the docs and all of
the other SDKs use the name `sorted_set_increment_score`. This fixes
the name to match the docs and other SDKs.
=> feat: bug fix - sorted_set_increment should be named sorted_set_increment_score

examples/prepy310/topic_subscribe_async.py, examples/py310/topic_subscribe_async.py
Restoring return statements for closed async streams.
=> fix: add back return statements for closed streams

src/momento/auth/credential_provider.py, src/momento/auth/momento_endpoint_resolver.py, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/aio/_vector_index_grpc_manager.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_grpc_manager.py
For MVI data plane calls, we were using `cache` as the endpoint prefix; this PR updates it to use `vector`. Note that for legacy tokens, we do not have a new JWT claim, so we will be using `cache` as the prefix for that as well.
Also, for control plane operations, the endpoint prefix is still `control`.
=> chore: use vector endpoint for MVI API calls

examples/poetry.lock, examples/pyproject.toml
bump examples to sdk 1.9.0. This version has the latest MVI changes and examples will now succeed.
=> chore: bump examples to sdk 1.9.0 for MVI

src/momento/vector_index_client_async.py
The docstring for `add_item_batch` was out of sync between the async
and synchronous clients. This fixes that.
=> docs: fix add item batch documentation for the async client

examples/poetry.lock, examples/py310/doc-examples-python-apis.py, examples/pyproject.toml
Addresses the python part of [#459](https://github.com/momentohq/dev-eco-issue-tracker/issues/459) by adding code snippets for instantiating a topic client, publishing to a topic, and subscribing to a topic. These examples will be used [on this page](https://docs.momentohq.com/develop/api-reference/topics).
=> chore: add docs examples for using topics

src/momento/requests/vector_index/item.py, tests/momento/requests/vector_index/test_item.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
Previously the SDK gave a vague error for bad input data. Current
metadata only supports string-valued items. When a user passed a (for
example) integer they would get an error of type "UNKNOWN" with detail
"SDK encountered an error".
This commit checks the metadata types upon serialization and generates
a nice, readable message and remediation.
A more comprehensive solution would involve using dynamic type checking
across the board such as with the pydantic library.
=> fix: validate vector index item metadata on serialization

poetry.lock, pyproject.toml, src/momento/requests/vector_index/item.py, src/momento/responses/vector_index/data/search.py, tests/momento/requests/vector_index/test_item.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
In the previous version of the service, we only supported
string-valued metadata. In the latest version, we support the
following value types:
- string
- int
- float
- bool
- list of strings
We update the `Item` class to support serializing these types and the
`SearchHit` class to deserialize.
=> feat: support more vector item metadata value types

tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
Previously we verified that we can create an index with the default
similarity metric. In this commit we add a test to explicitly check
that the behavior is consistent with `COSINE_SIMILARITY`.
=> chore: explicitly test behavior when using default similarity metric

src/momento/config/transport/grpc_configuration.py, src/momento/config/transport/transport_strategy.py, src/momento/config/vector_index_configuration.py, src/momento/internal/_utilities/_channel_credentials.py, src/momento/internal/aio/_vector_index_control_client.py, src/momento/internal/aio/_vector_index_grpc_manager.py, src/momento/internal/synchronous/_vector_index_grpc_manager.py, tests/momento/config/test_vector_index_config.py
Adds a `with_root_certificates_pem` to read a certificate pem
file. Exposes a `with_root_certificates_pem` method to the top level
of `VectorIndexConfiguration` for convenience. The clients are
instantiated with either the default ssl channel creds or ones using
the root certificates, if available.
=> feat: allow custom root certificates in vector index client config

src/momento/config/configuration.py, src/momento/config/transport/transport_strategy.py, src/momento/config/vector_index_configuration.py, src/momento/internal/_utilities/_channel_credentials.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/aio/_vector_index_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/internal/synchronous/_vector_index_grpc_manager.py, tests/momento/config/test_config.py, tests/momento/config/test_vector_index_config.py
Like the previous PR for the vector client, this adds the ability to
set the root certificate for the cache client. We add methods to the
top level configuration for convenience. Unit and integration tests
exercise the happy and error paths.
The integration tests for the happy path also exercise when a custom root
certificate is added. Because this reuses a cached certs, we
comment out the tests. They serve as documentation to reproduce good
behavior.
A future PR will add this to the topics client.
=> feat: allow custom root certificates in cache client

poetry.lock, pyproject.toml, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/vector_index_client.py, src/momento/vector_index_client_async.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
Add the ability to specify a score threshold to prune search results
server side. Search hit distances must meet this threshold to be
included.
For euclidean similarity, scores lower than the threshold are
included; for inner product and cosine similarity, higher scores are
included.
Bumps the protos, implements the feature, and adds tests.
=> feat: add mvi search score threshold

pyproject.toml, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/responses/vector_index/__init__.py, src/momento/responses/vector_index/data/search.py, src/momento/responses/vector_index/data/search_and_fetch_vectors.py, src/momento/responses/vector_index/data/utils.py, src/momento/vector_index_client.py, src/momento/vector_index_client_async.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py, tests/utils.py
Add MVI `search_and_fetch_vectors` method and integration tests. This new method performs a `search` as usual, but returns the vectors associated with the search hits. That is, the only change in behavior comes down to the response. 
Because of this, we refactor the search tests to work against both `search` and `search_and_fetch_vectors`. We make use of pytest's parameterized test feature to do this.
=> feat: add mvi search and fetch vectors method

src/momento/responses/vector_index/data/search.py, src/momento/responses/vector_index/data/search_and_fetch_vectors.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
To align with the `scoreThreshold` option in `search`, and for
clarity in that the search hits are not ordered by `distance` (which
is lower or better), but by `score` (which could be higher or better,
or a blend of multiple things), we rename the `distance` property to
`score`.
=> refactor: mvi rename distance to score

src/momento/responses/vector_index/control/list.py, tests/momento/vector_index_client/test_control.py, tests/momento/vector_index_client/test_control_async.py
Previously a list indexes success response only contained a list of
index names. We refactor this to contain a list of VectorIndexInfo
objects, each of which can contain encapsulate many details. To start
we only include the index name.
We update the integration tests and indexes along with this.
=> refactor: mvi list indexes response to contain index info detail

poetry.lock, pyproject.toml, src/momento/responses/vector_index/data/search.py, src/momento/responses/vector_index/data/search_and_fetch_vectors.py
Bumps `momento-wire-types` and updates backend to read `score` from `SearchHit` and `SearchAndFetchVectorsHit`.
=> chore: bump protos and consume mvi searchhit update

src/momento/responses/vector_index/data/search.py
Until the langchain update is approved, we will have the distance
property as an alias for score.
=> chore: temporarily add score alias for langchain compatibility

poetry.lock, pyproject.toml, src/momento/internal/aio/_vector_index_control_client.py, src/momento/internal/synchronous/_vector_index_control_client.py, src/momento/responses/vector_index/control/list.py
Update MVI list and create index backends for latest protos. The developer-facing API remains the same; this is only an internal update.
=> chore: update mvi backend for create/list indexes updates

src/momento/responses/vector_index/data/search.py
We previously had `distance` as an alias for `score` until the
langchain integration update was merged. As that has been merged, we
no longer need this.
=> chore: remove unnecessary score alias

.github/workflows/on-pull-request.yml
The examples use a cache called `test-cache`. This is hard-coded and
easy to read for a nice user experience. Because of this, we need to
run the examples sequentially or else one job may delete the cache
while another job is still working.
=> ci: fix example clobbering

poetry.lock, pyproject.toml
Mypy has been 1.0 and VS Code plugins require 1.0. This PR bumps the
mypy dep.
=> chore: bump mypy dependency

src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/responses/vector_index/data/get_item_batch.py, src/momento/responses/vector_index/data/get_item_metadata_batch.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
We reserve `values` for getters, consistent with the cache
usage. `hits` is standard for search results though.
=> refactor: prefer `values` accessor over `hits`

examples/py310/doc-examples-python-apis.py
Adds `get_item_batch` and `get_item_metadata_batch` to example snippets.
=> chore: update doc examples for `get item` methods

poetry.lock, pyproject.toml, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/requests/vector_index/__init__.py, src/momento/requests/vector_index/filter_field.py, src/momento/requests/vector_index/filters.py, src/momento/vector_index_client.py, src/momento/vector_index_client_async.py, tests/momento/requests/vector_index/test_filters.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
Implements filter expressions for MVI. Filter expressions are additional "where" clauses on metadata fields. The search results are ordered based on query-content vector similarity; and an item is subject to inclusion if the item satisfies the field expression.
=> feat: mvi filter expressions

poetry.lock, pyproject.toml
The count items response has been changed to return a uint64 instead
of uint32. That way we can account for index sizes greater than 4
billion items in size.
=> chore: bump protos for count items uint64

poetry.lock, pyproject.toml, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/vector_index_client.py, src/momento/vector_index_client_async.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
In preparation for using filters across the two `get` methods and also
`delete`, we rename `filter_expression` to `filter`. In general these methods
may allow a user to pass a filter expression or, for convenience, a list of ids
(strings).
=> refactor: mvi filter expression arg rename

poetry.lock, pyproject.toml, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/responses/vector_index/data/get_item_batch.py, src/momento/responses/vector_index/data/get_item_metadata_batch.py
We are in the process of migrating MVI `delete item batch`, `get item batch`, and `get item metadata batch` to use a filter expression to select items to delete (get) as opposed to a list of id's. For convenience, we will still allow users to select items with a list of id's from the top level methods. This PR migrates the backend.
As part of the migration we are also moving away from the hit/miss pattern for `get item batch` and `get item metadata batch` response messages. While the hit/miss pattern made sense for when we only selected items by id, it no longer makes sense for when a user supplies a general filter expression. What's more, previously when we read the hit/miss responses, we built a dictionary containing only the hits, so the distinction wasn't as important.
In future PRs …
=> refactor: use mvi filter fields for get/delete items

src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, src/momento/vector_index_client.py, src/momento/vector_index_client_async.py, tests/momento/vector_index_client/test_data.py, tests/momento/vector_index_client/test_data_async.py
Adds an overload MVI `delete_item_batch` to allow users to delete items by not just a list of ids, but also a more general filter expression. We maintain the option of providing a list of ids for convenience. This PR adds integration tests and updates the documentation.
=> feat: add mvi delete by filter overload

src/momento/vector_index_client.py, src/momento/vector_index_client_async.py
Previously the delete by filter docstring was incorrect, stating that
the filter expression "filters items by ID". The filter expression
matches items to be deleted.
=> docs: improve delete by filter docstring

src/momento/internal/_utilities/__init__.py, src/momento/internal/_utilities/_grpc_channel_options.py, src/momento/internal/_utilities/_time.py, src/momento/internal/aio/_scs_data_client.py, src/momento/internal/aio/_vector_index_data_client.py, src/momento/internal/synchronous/_scs_data_client.py, src/momento/internal/synchronous/_vector_index_data_client.py, tests/momento/internal/_utilities/test_time.py
This PR corrects two bugs.
First we add a utility function to convert timedelta objects to milliseconds, unit tests, and refactor code to use this across the board. Previously we were converting timedeltas to milliseconds in several places which led to bugs when calling `.seconds` (not fractional) vs `total_seconds()` (fractional). Calling the former was truncating the milliseconds portion.
Second we correct a bug the gRPC timeout. After reading from the config, we converted the timedelta to total whole seconds. This again truncated the milliseconds portion; because the gRPC parameter accepts fractional seconds, we should not have been truncating.
=> fix: timedelta to ms conversion and timedelta to deadline conversion

src/momento/internal/_utilities/_grpc_channel_options.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/aio/_vector_index_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/internal/synchronous/_vector_index_grpc_manager.py
Follow-up to #441 after we determined control plane connections should not have keepalives.
Also propagating the grpc channel options changes over to the synchronous code as well.
=> fix: disable keepalive in grpc channel options for control plane clients and set grpc channel options in synchronous code

src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py, tests/momento/cache_client/test_init.py, tests/momento/cache_client/test_init_async.py
Eager connection should raise the error instead of logging the failure.
Tested locally and saw `RuntimeError: Failed to connect to Momento's server within given eager connection timeout` and the stack trace.
=> chore: eager connection should fail fast

examples/lambda/README.md
The previous PR had incorrect markdown for the tip section. This
corrects that.
=> chore: fix markdown in lambda zip example

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-main-branch.yml, .github/workflows/on-push-to-release-branch.yml
Updates the CI workflows to use `ubuntu-24.04` for python 3.9+ and `ubuntu-20.04` for python 3.7 and 3.8. Previously we could not run on `ubuntu-22.04` due to a difficult-to-diagnose timeout problem. This timeout problem manifested on Azure VMs with ubuntu-22.04 but not on other platforms.
This problem does not manifest on `ubuntu-24.04`, so we can use that where possible. Because python 3.7 and python 3.8 are not available on `ubuntu-24.04`, we still run those on `ubuntu-20.04`. At some point we can look in to installing via `pyenv` or manually on `ubuntu-24.04`.
=> chore: use ubuntu-24.04 for ci where possible

.github/workflows/on-pull-request.yml, .github/workflows/on-push-to-release-branch.yml, src/momento/internal/_utilities/__init__.py, src/momento/internal/_utilities/_client_type.py, src/momento/internal/_utilities/_python_runtime_version.py, src/momento/internal/aio/_add_header_client_interceptor.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py
Adds the service client type to the `agent` header details, and adds a
new `runtime-version` header for the cache and topics clients.
The runtime version information looks like:
major.minor.patch (releasetype serial)
for example:
`python 3.11.2 (final 0)`
The releasetype covers alpha vs beta vs experimental vs final
versions. The serial covers particular alpha/beta release versioning.
We also fix the poetry installation in CI for python 3.7. Previously we installed poetry first, then installed python setting the cache as poetry. On older versions of ubuntu this does not work since it uses the wrong python version to install poetry. So we change the installation order to how it was before: first install python, then install poetry.
=> chore: add agent details and new runtime version header

src/momento/internal/_utilities/_momento_version.py
A user reports that in some environments the Momento version
detection code raises a `ModuleNotFoundError` as opposed to 
`ImportError`. We modify the try-except to also catch that error 
as the user reports this in a python 3.8 environment.
=> fix: when detecting momento version also catch `ModuleNotFoundError`

examples/py310/order_system.py, examples/py310/patterns.py
Adds an example demonstrating how a restaurant could use caching and
topics to store order status and communicate with wait staff.
Example output:
```
2024-09-13 15:25:47,965 INFO     momentosdk Creating cache with name: cache
2024-09-13 15:25:48,226 INFO     order-system-example Using existing cache.
2024-09-13 15:25:48,481 INFO     order-system-example Waiter subscribed to order updates.
2024-09-13 15:25:49,227 INFO     order-system-example The waiter is ready to update customers.
2024-09-13 15:25:49,227 INFO     order-system-example Kitchen updating order 1 with status: Preparing
2024-09-13 15:25:49,488 INFO     order-system-example Updated order status: Order 1: Preparing
2024-09-13 15:25:49,752 INFO     order-system-example Waiter received order update: Order 1: Preparing
2024-09-13 …
```
=> feat: order system example

src/momento/internal/_utilities/_momento_version.py
We temporarily fall back to a manually provided version number when
the `dist-info` METADATA is absent. This situation occurs in some
frameworks like `serverless` which strip this for a slim build.
In the near future we will refactor this code so that CI sets the
version number in the file and we do not rely on metadata reflection.
=> chore: fall back manual version when dist-info absent

Makefile, src/momento/__init__.py, src/momento/auth/access_control/disposable_token_scope.py, src/momento/auth/access_control/disposable_token_scopes.py, src/momento/auth/access_control/permission_scope.py, src/momento/auth/access_control/permission_scopes.py, src/momento/auth/credential_provider.py, src/momento/auth/momento_endpoint_resolver.py, src/momento/auth_client.py, src/momento/auth_client_async.py, src/momento/config/auth_configuration.py, src/momento/config/auth_configurations.py, src/momento/internal/_utilities/_client_type.py, src/momento/internal/_utilities/_permissions.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/aio/_scs_token_client.py, src/momento/internal/codegen.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_token_client.py, src/momento/responses/__init__.py, src/momento/responses/auth/generate_disposable_token.py, src/momento/responses/response.py, src/momento/utilities/expiration.py, src/momento/utilities/shared_sync_asyncio.py, tests/conftest.py, tests/momento/auth_client/test_auth_client.py, tests/momento/auth_client/test_auth_client_async.py, tests/momento/auth_client/test_permissions.py
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1016
Will follow up with examples/docs updates.
To add the generate_disposable_token api, we needed to implement the AuthClient and permissions classes as well.
Note: Go sdk's permissions structure includes topic name prefix as well, but JS sdk does not. Should topic name prefix be added here?
=> feat: add auth client and generate_disposable_token api

src/momento/auth_client.py, src/momento/auth_client_async.py, src/momento/cache_client.py, src/momento/cache_client_async.py, src/momento/internal/_utilities/__init__.py, src/momento/internal/_utilities/_data_validation.py, src/momento/internal/_utilities/_permissions.py, src/momento/internal/aio/_scs_token_client.py, src/momento/internal/synchronous/_scs_token_client.py, src/momento/responses/auth/generate_disposable_token.py, src/momento/utilities/__init__.py, src/momento/utilities/shared_sync_asyncio.py, tests/momento/auth_client/test_auth_client.py, tests/momento/auth_client/test_auth_client_async.py
Ran into an error while writing new dev docs examples. Created a new `str_to_bytes` util function in the package proper rather than using the one from `tests.utils`. Bug appears to be fixed when running the examples against a locally built version of the package now.
```
File "/Users/anita/client-sdk-python/examples/.venv/lib/python3.10/site-packages/momento/internal/_utilities/_permissions.py", line 28, in <module>
from tests.utils import str_to_bytes
ModuleNotFoundError: No module named 'tests'
```
Also moved the two validators to internal utils where the others are.
=> fix: do not use test util in package

src/momento/responses/__init__.py
Allows for `from momento.responses import GenerateDisposableToken` instead of `from momento.responses.auth.generate_disposable_token import GenerateDisposableToken`
=> fix: add GenerateDisposableToken Success and Error subclasses to responses init file

.github/workflows/on-push-to-main-branch.yml, .release-please-manifest.json, src/momento/__init__.py
Adds a release please job with v4.
Unlike v3, which we have in other repos, v4 requires a manifest
file for most of the options. We add that to the root of the
project. Also unlike v3, we also have to explicitly pass the release please
outputs from the release-please job to the publish job.
We have also verified setting the version in source. That happens with
the extra-files property in the manifest. The version in the main
`__init__` requires a stub version so the release please regex can
substitute it.
In an upcoming PR we will fill out the publish job in `on-push-to-main`.
=> ci: set up with release please v4 and stub publish step

.release-please-manifest.json
Removes trailing comma in manifest, which was an error.
Release-Version: 1.23.4
=> ci: remove trailing comma in manifest

.release-please-manifest.json
Previously the manifest did not specify the base version for the first
release. We set that here explicitly so the first release has the
correct changelog.
Release-As: 1.23.4
=> fix: set the release please base version in the manifest

.github/workflows/on-push-to-main-branch.yml
Ports the publish steps from the former release workflow. We have
already verified in a separate repo that the conditional execution
works as expected.
=> ci: add publish job to publish from release-please

pyproject.toml, src/momento/internal/_utilities/_permissions.py, tests/momento/auth_client/test_permissions.py
Adds per-module ignores for generated auth protobuf.
=> fix: lint errors on 3.10+ for auth protos

.github/workflows/on-push-to-main-branch.yml
Recently merged #485 (marked as a `chore` commit) but a release-please PR wasn't opened.
This PR adds the missing `changelog-types` field to the release-please github action to ensure all `feat`, `fix`, and `chore` commits are picked up in the next release.
=> chore: release-please workflow should pick up feat, fix, and chore commits

.github/workflows/on-push-to-main-branch.yml, .release-please-manifest.json
Follow up to #486 -- release-please still did not produce a new PR to cut a new release.
~~I think switching the release-please github actions version to `v3` to match what the other SDKs use will allow the `changelog-types` field to be picked up and parse our commits correctly.~~
~~Update: using `v4` shouldn't be a problem. I think we're just missing the argument to specify the path to the manifest, as shown in their [example](https://github.com/googleapis/release-please-action?tab=readme-ov-file#advanced-release-configuration).~~
Found an [issue](https://github.com/googleapis/release-please-action/issues/941) in the release-please action that seems to show the same problem (action ends with "No user facing commits found since ... - skipping"), and the solution was to move all the …
=> chore: specify path to release-please manifest

.release-please-manifest.json, release-please-config.json
Put config settings in the config and only the version in the
manifest.
In v4 the manifest should have the release-please-maintained
package version, whereas the config should have everything else.
See:
- https://github.com/googleapis/release-please/blob/main/release-please-config.json
- https://github.com/googleapis/release-please-action/issues/941#issuecomment-2053795782
=> ci: use release-please-config vs manifest

src/momento/internal/_utilities/_grpc_channel_options.py
- Based on the commit [here](https://github.com/googleapis/gapic-generator/pull/2817/files), dynamic txt lookup for dns resolution flag is disabled by default in grpc-python. 
- This commit explicitly disables it too.
```
sudo tcpdump -i any -vvv port 53 | grep -i cache.cell-alpha-dev.preprod.a.momentohq.com           ─╯
Password:
tcpdump: data link type PKTAP
tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), snapshot length 524288 bytes
10.0.0.249.62558 > pd1nsc3.st.vc.shawcable.net.domain: [udp sum ok] 23436+ AAAA? cache.cell-alpha-dev.preprod.a.momentohq.com. (62)
10.0.0.249.62558 > pd1nsc3.st.vc.shawcable.net.domain: [udp sum ok] 25894+ A? cache.cell-alpha-dev.preprod.a.momentohq.com. (62)
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.62558: [udp sum ok] 23436 q: AAAA? …
```
=> fix: disable dynamic DNS service config

src/momento/config/topic_configuration.py, src/momento/config/topic_configurations.py, src/momento/config/transport/topic_grpc_configuration.py, src/momento/config/transport/topic_transport_strategy.py, src/momento/internal/_utilities/_grpc_channel_options.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/aio/_scs_pubsub_client.py, src/momento/internal/synchronous/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_pubsub_client.py, tests/conftest.py
Closes [Issue #1133](https://github.com/momentohq/dev-eco-issue-tracker/issues/1133)
Publish deadline was not getting set. This PR fixes that and adds a TopicGrpcConfiguration and TopicTransportStrategy to make the publish timeout configurable.
=> feat: add topic grpc config and transport strategy and make sure publish deadline is set

src/momento/auth/credential_provider.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_scs_grpc_manager.py
Add a credential provider to connect to Momento Local.
Update the gRPC managers to be able to create insecure channels for connecting to Momento Local.
=> feat: Add a credential provider for Momento Local

src/momento/config/auth_configuration.py, src/momento/config/configuration.py, src/momento/config/middleware/aio/middleware_metadata.py, src/momento/config/middleware/models.py, src/momento/config/middleware/synchronous/middleware_metadata.py, src/momento/config/topic_configuration.py, src/momento/internal/aio/_middleware_interceptor.py, src/momento/internal/aio/_scs_grpc_manager.py, src/momento/internal/synchronous/_middleware_interceptor.py
Remove the configuration base classes. These aren't used by any of the code that takes a configuration, so users can't implement new configurations with them and pass them into clients. I'm removing them instead of making the clients use them because config base classes make it difficult to add new configuration options breaking potential user implementations.
Make the middleware classes into data classes. The existing standard classes with getters isn't pythonic.
=> chore: remove configuration bases and make middleware more pythonic

.github/workflows/momento-local-tests.yml, .github/workflows/on-pull-request.yml, Makefile, pyproject.toml, src/momento/retry/fixed_timeout_retry_strategy.py, tests/conftest.py, tests/momento/local/momento_error_code_metadata.py, tests/momento/local/momento_local_async_middleware.py, tests/momento/local/momento_local_metrics_collector.py, tests/momento/local/momento_local_middleware.py, tests/momento/local/momento_local_middleware_args.py, tests/momento/local/momento_rpc_method.py, tests/momento/local/test_fixed_count_retry_strategy.py, tests/momento/local/test_fixed_count_retry_strategy_async.py
Add a middleware that lets tests control Momento Local with metadata and can collect metrics about retries.
Add sync and async tests for the fixed count retry strategy.
Update the aio retry interceptor to stop if from ignoring the result of a future in some cases.
Add a make target for local tests.
Add a github action to run the local tests.
=> chore: add tests for the fixed count retry strategy

src/momento/internal/aio/_scs_pubsub_client.py, src/momento/internal/synchronous/_scs_pubsub_client.py, tests/momento/topic_client/test_topics.py, tests/momento/topic_client/test_topics_async.py
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1149
The `timeout` argument to subscribe calls works to set a timeout, which is already passed into the topic client for the publish calls. 
Also added tests to verify that setting a short timeout will trigger the DEADLINE_EXCEEDED error for subscribe calls.
=> chore: add timeout to topic subscribe
